In [1]:
import numpy as np

a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  

b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])

<type 'numpy.ndarray'>
(3L,)
(1, 2, 3)
[5 2 3]
(2L, 3L)
(1, 2, 4)


In [3]:
#NP.FULL CREATES CONSTANT ARRAY
#NP.EYE CREATES IDENTITY MATRIX
#NP.RANDOM CREATES AN ARRAY FILLED WITH RANDOM VALUE

In [2]:
a = np.zeros((2,2))   
print(a)       

b = np.ones((1,2))    
print(b)              

c = np.full((2,2), 7) 
print(c)              
                      

d = np.eye(2)         
print(d)              
                      

e = np.random.random((2,2))  
print(e)                     
                           

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.75309338  0.67514603]
 [ 0.352773    0.26638263]]


In [4]:
#ARRAY MATHS

In [5]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [6]:
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [7]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [8]:
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [9]:
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [11]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [12]:
v = np.array([9,10])
w = np.array([11, 12])

In [ ]:
#TAKING DOT PRODUCT OF ARRAY

In [13]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [14]:
print(x.dot(v))
print(np.dot(x, v))

[ 29.  67.]
[ 29.  67.]


In [15]:
print(x.dot(y))
print(np.dot(x, y))

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [16]:
#TRANSPOSE OF MATRIX

In [17]:
x1 = np.array([[1,2], [3,4]])

In [18]:
print(x1)    
print(x1.T) 

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
